# Build settings
destination: ../build
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-postcss-v2
liquid:
  error_mode: strict
sass:
  sass_dir: _scss
  style: nested
postcss:
  cache: false
timezone: Etc/GMT
future: true


# Site settings
title: The Library Innovation Lab at Harvard University
description: >
  The Library Innovation Lab is growing knowledge and community by bringing library principles to technological frontiers.
baseurl: ""
url: "https://lil.law.harvard.edu"
sharing-image: "thumbs/800x800r/lil-primary-black.png"

# Contact
email: lil@law.harvard.edu
twitter_account_name: HarvardLIL
twitter_url: https://twitter.com/harvardlil
linkedin_account_name: libraryinnovationlab
linkedin_url: https://www.linkedin.com/company/libraryinnovationlab/
facebook_url: https://www.facebook.com/HarvardLibraryInnovationLab/
github_account_name: harvard-lil
github_url:  https://github.com/harvard-lil
address_name: The Library Innovation Lab
address_street1: The Reginald F. Lewis Law Center
address_street2: 1557 Massachusetts Avenue
address_map_url: https://www.google.com/maps/place/1557+Massachusetts+Ave,+Cambridge,+MA+02138/@42.3782483,-71.1213313,17z/data=!3m1!4b1!4m5!3m4!1s0x89e37741bde17be1:0xf64e9368998f6967!8m2!3d42.3782444!4d-71.1191426
address_city_state: Cambridge, MA 02138

# Blog Feeds
blog_feed_title: The Harvard Library Innovation Lab

# Collections
collections:
  our_work:
    output: true
    permalink: /our-work/:slug/
  our_work_pageless:
    output: false
  events:
    output: true
    permalink: /events/:slug/

# Plugins
news_feed_for:
  - our_work

contributors_feed_for:
  - our_work

# Defaults
defaults:
  - scope:
      path: ""
      type: our_work
    values:
      layout: our_work
      type: our_work
  - scope:
      path: ""
      type: events
    values:
      layout: event
      type: event
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      type: post
      permalink: blog/:year/:month/:day/:title/
  - scope:
      path: ""
    values:
      sharing-card-type: summary

# Feature Flags
show_blog_featured_tags: true

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 12

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: 'Page :num of :max | :title'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  # tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  # locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
 # trail:
 #   before: 2
 #   after: 2

############################################################

############################################################
# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:

  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true

  # Category pages, omit entire config element to disable
  categories:
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts:
      - 'tag_or_category.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: 'Posts in category ":cat" | Blog'
    # Optional, the permalink for the  pagination page (:cat is replaced),
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/blog/category/:cat/'
    slugify:
      mode: default
      cased: true

  collections:
    enabled: false

  # Tag pages, omit to disable
  tags:
    layouts:
      - 'tag_or_category.html'
    title: 'Posts tagged ":tag" | Blog' # :tag is replaced by the tag name
    permalink: '/blog/tag/:tag/'
    slugify:
      mode: default
      cased: true
